"""Write the substructure element sets, materials and sections for the Abaqus deck.

The deck DRAGen_RVE.inp already contains one `*Elset Set-<grain>` per grain. This module adds a
second, finer partition -- one material region per block (substructure) or per grain (everything
else) -- so each block can carry its own orientation.

Three files are produced, deliberately under names of their own:

    substructure.inp             PAG-/PACKET-/BLOCK-/MATREG- element sets  (part level)
    SubstructureSections.inp     one *Solid Section per MATREG            (part level)
    SubstructureMaterials.inp    one *Material per MATREG                 (model level)

`Materials.inp` is left untouched: when subs_flag is set, dragen/generation/Mesher3D.py includes
these files *instead* of the per-grain materials and sections, so no element ever ends up in two
solid sections.

Element ids are `cell index + 1`: rve-part.inp and rve-part.vtk are written from the same mesh by
pv.save_meshio, so cell order and Abaqus element numbering agree.
"""
import os

import numpy as np
import pandas as pd
import pyvista as pv

from dragen.substructure import validation
from dragen.substructure.config import SubsConfig
from dragen.utilities.InputInfo import RveInfo

SUBSTRUCTURE_INP = 'substructure.inp'
MATERIALS_INP = 'SubstructureMaterials.inp'
SECTIONS_INP = 'SubstructureSections.inp'
GRAINDATA_CSV = 'graindata_blocks_materialregions.csv'
MATREGION_VTK = 'rve_with_orientations_and_matregions.vtk'


def _write_elset(f, name: str, element_ids: np.ndarray, per_line: int = 16) -> None:
    if len(element_ids) == 0:
        return

    f.write(f'*Elset, elset={name}\n')

    for i in range(0, len(element_ids), per_line):
        f.write(', '.join(str(eid) for eid in element_ids[i:i + per_line]) + '\n')


def build_material_regions(mesh: pv.DataSet):
    """One 1-based material region per block (substructure) or per grain+phase (everything else)."""
    grain_id = np.asarray(mesh.cell_data['GrainID']).astype(int)
    phase_id = np.asarray(mesh.cell_data['phaseID']).astype(int)
    block_id = np.asarray(mesh.cell_data['BlockID']).astype(int)
    sub_flag = np.asarray(mesh.cell_data['SubstructureFlag']).astype(int)

    key_to_region = {}
    region_keys = []
    region_per_cell = np.full(mesh.n_cells, -1, dtype=np.int32)

    for cell_id in range(mesh.n_cells):
        if sub_flag[cell_id] == 1:
            if block_id[cell_id] < 1:
                raise ValueError(f'Cell {cell_id}: SubstructureFlag=1 but BlockID < 1')
            key = ('block', int(block_id[cell_id]))
        else:
            if block_id[cell_id] != -1:
                raise ValueError(f'Cell {cell_id}: SubstructureFlag=0 but BlockID != -1')
            key = ('grain', int(phase_id[cell_id]), int(grain_id[cell_id]))

        if key not in key_to_region:
            key_to_region[key] = len(region_keys) + 1
            region_keys.append(key)

        region_per_cell[cell_id] = key_to_region[key]

    if np.any(region_per_cell < 1):
        raise ValueError('Some cells did not receive a MaterialRegionID.')

    return region_per_cell, region_keys


def _check_one_orientation_per_region(region_ids, phi1, PHI, phi2) -> None:
    for rid in np.unique(region_ids):
        mask = region_ids == rid
        unique_values = np.unique(np.column_stack([phi1[mask], PHI[mask], phi2[mask]]), axis=0)

        if unique_values.shape[0] != 1:
            raise ValueError(f'MaterialRegionID {rid} has {unique_values.shape[0]} distinct '
                             'orientations, expected 1.')

    RveInfo.LOGGER.info('Orientation per MaterialRegionID: OK')


def _write_substructure_inp(cfg: SubsConfig, mesh: pv.DataSet, filename: str) -> None:
    grain_id = np.asarray(mesh.cell_data['GrainID']).astype(int)
    packet_id = np.asarray(mesh.cell_data['PacketID']).astype(int)
    block_id = np.asarray(mesh.cell_data['BlockID']).astype(int)
    region_id = np.asarray(mesh.cell_data['MaterialRegionID']).astype(int)

    with open(filename, 'w') as f:
        f.write('** ================================\n')
        f.write('** Substructure and material-region element sets\n')
        f.write('** Generated by DRAGen\n')
        f.write('** ================================\n\n')

        f.write('** -------- PAG / Grain level --------\n')
        for gid in np.unique(grain_id):
            _write_elset(f, f'PAG-{int(gid)}', np.where(grain_id == gid)[0] + 1)
        f.write('\n')

        f.write('** -------- Packet level: real packets only --------\n')
        for pid in np.unique(packet_id[packet_id > 0]):
            _write_elset(f, f'PACKET-{int(pid)}', np.where(packet_id == pid)[0] + 1)
        f.write('\n')

        f.write('** -------- Block level: real blocks only --------\n')
        for bid in np.unique(block_id[block_id > 0]):
            _write_elset(f, f'BLOCK-{int(bid)}', np.where(block_id == bid)[0] + 1)
        f.write('\n')

        f.write('** -------- Material regions: all cells --------\n')
        covered = 0
        for rid in np.unique(region_id):
            cells = np.where(region_id == rid)[0] + 1
            covered += len(cells)
            _write_elset(f, f'MATREG-{int(rid)}', cells)
        f.write('\n')

    if covered != mesh.n_cells:
        raise ValueError(f'MATREG element sets cover {covered} of {mesh.n_cells} elements.')

    RveInfo.LOGGER.info(f'Saved: {filename} ({mesh.n_cells} elements fully covered by MATREG sets)')


def _write_materials_inp(cfg: SubsConfig, region_ids: np.ndarray, filename: str) -> None:
    with open(filename, 'w') as f:
        f.write('** MATERIALS\n')
        f.write('** Generated by DRAGen: one material per MaterialRegionID\n')
        f.write('**\n')

        for rid in np.unique(region_ids):
            f.write(f'*Material, name=MATREG_{int(rid)}\n')
            f.write('*Depvar\n')
            f.write(f'{cfg.depvar_number},\n')
            f.write('*User Material, constants=2\n')
            f.write(cfg.user_material_constants + '\n')

    RveInfo.LOGGER.info(f'Saved: {filename}')


def _write_sections_inp(cfg: SubsConfig, region_ids: np.ndarray, filename: str) -> None:
    with open(filename, 'w') as f:
        f.write('** SECTIONS\n')
        f.write('** Generated by DRAGen: one section per MaterialRegionID\n')
        f.write('**\n')

        for rid in np.unique(region_ids):
            f.write(f'*Solid Section, elset=MATREG-{int(rid)}, '
                    f'controls={cfg.section_controls}, material=MATREG_{int(rid)}\n')
            f.write('*Hourglass Stiffness\n')
            f.write('1., , 1., 1.\n')

    RveInfo.LOGGER.info(f'Saved: {filename}')


def _write_orientation_table(cfg: SubsConfig, mesh: pv.DataSet, filename: str) -> None:
    region_ids = np.asarray(mesh.cell_data['MaterialRegionID']).astype(int)
    grain_id = np.asarray(mesh.cell_data['GrainID']).astype(int)
    phase_id = np.asarray(mesh.cell_data['phaseID']).astype(int)
    block_id = np.asarray(mesh.cell_data['BlockID']).astype(int)
    packet_id = np.asarray(mesh.cell_data['PacketID']).astype(int)
    sub_flag = np.asarray(mesh.cell_data['SubstructureFlag']).astype(int)

    phi1 = np.asarray(mesh.cell_data['phi1'], dtype=float)
    PHI = np.asarray(mesh.cell_data['PHI'], dtype=float)
    phi2 = np.asarray(mesh.cell_data['phi2'], dtype=float)

    rows = []

    for rid in np.unique(region_ids):
        mask = region_ids == rid
        unique_values = np.unique(np.column_stack([phi1[mask], PHI[mask], phi2[mask]]), axis=0)

        rows.append({
            'Region': 'MaterialRegion',
            'MaterialRegionID': int(rid),
            'phaseID': int(np.unique(phase_id[mask])[0]),
            'GrainID_unique': ','.join(map(str, np.unique(grain_id[mask]))),
            'PacketID_unique': ','.join(map(str, np.unique(packet_id[mask]))),
            'BlockID_unique': ','.join(map(str, np.unique(block_id[mask]))),
            'SubstructureFlag_unique': ','.join(map(str, np.unique(sub_flag[mask]))),
            'phi1': unique_values[0, 0],
            'PHI': unique_values[0, 1],
            'phi2': unique_values[0, 2],
            'size': cfg.grain_size_value,
            'n_cells': int(np.count_nonzero(mask)),
        })

    pd.DataFrame(rows).to_csv(filename, index=False, sep=':')

    RveInfo.LOGGER.info(f'Saved: {filename}')


def write(cfg: SubsConfig, mesh: pv.DataSet) -> None:
    required = ['GrainID', 'phaseID', 'PacketID', 'BlockID', 'SubstructureFlag',
                'phi1', 'PHI', 'phi2']
    for array in required:
        if array not in mesh.cell_data:
            raise KeyError(f'Missing required cell_data array: {array}')

    grain_id = np.asarray(mesh.cell_data['GrainID']).astype(int)
    packet_id = np.asarray(mesh.cell_data['PacketID']).astype(int)
    block_id = np.asarray(mesh.cell_data['BlockID']).astype(int)

    phi1 = np.asarray(mesh.cell_data['phi1'], dtype=float)
    PHI = np.asarray(mesh.cell_data['PHI'], dtype=float)
    phi2 = np.asarray(mesh.cell_data['phi2'], dtype=float)

    validation.check_positive_ids_continuous(grain_id, 'GrainID')
    validation.check_positive_ids_continuous(packet_id, 'PacketID')
    validation.check_positive_ids_continuous(block_id, 'BlockID')
    validation.check_substructure_consistency(mesh)

    if not (np.all(np.isfinite(phi1)) and np.all(np.isfinite(PHI)) and np.all(np.isfinite(phi2))):
        raise ValueError('Euler angles contain NaN or Inf.')

    region_per_cell, _ = build_material_regions(mesh)
    mesh.cell_data['MaterialRegionID'] = region_per_cell

    validation.check_positive_ids_continuous(region_per_cell, 'MaterialRegionID')
    _check_one_orientation_per_region(region_per_cell, phi1, PHI, phi2)

    RveInfo.LOGGER.info(f'Abaqus material regions after substructuring: '
                        f'{len(np.unique(region_per_cell))}')

    # The deck files go next to DRAGen_RVE.inp, which *Includes them.
    _write_substructure_inp(cfg, mesh, os.path.join(cfg.store_path, SUBSTRUCTURE_INP))
    _write_materials_inp(cfg, region_per_cell, os.path.join(cfg.store_path, MATERIALS_INP))
    _write_sections_inp(cfg, region_per_cell, os.path.join(cfg.store_path, SECTIONS_INP))

    _write_orientation_table(cfg, mesh, cfg.path(GRAINDATA_CSV))

    mesh.save(cfg.path(MATREGION_VTK))
    RveInfo.LOGGER.info(f'Saved: {cfg.path(MATREGION_VTK)}')
